# Site settings
title: NAAS
email: naasact@outlook.com
description: >
  National Aeromodelling & Aviators Society

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://naas-act.github.io/ # the base hostname & protocol for your site
# git_address: https://github.com/aksakalli/jekyll-doc-theme
# git_edit_address: https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages
facebook: https://www.facebook.com/naasact/
youtube: https://www.youtube.com/channel/UCu2pUGqKC1YerR2qKrzbO4A

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
# bootwatch: paper
# bootwatch: paper-mod
# bootwatch: cerulean
bootwatch: cerulean-mod
# bootwatch: spacelab

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .ignore/
  - .attic/
  - .gitignore
  - README.md
timezone: Sydney/Australia
future: true

defaults:

- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _event-announcements
    type: event-announcements
  values:
    layout: event-announcement

- scope:
    path: past-events
  values:
    layout: past-event

- scope:
    path: ""
  values:
    layout: page

collections:
  posts:
    output: true
    permalink: /news/:path/
  event-announcements:
    output: true
    permalink: /event-announcements/:path/

plugins_dir:
  - jekyll-youtube

# plugins:
#   - jekyll-maps
