#! /bin/sh
_scripts/resize-images.sh img
_scripts/resize-images.sh events/img
_scripts/resize-images.sh gallery/facilities-img
_scripts/resize-images.sh gallery/gallery-img
_scripts/resize-images.sh gallery/history-img
_scripts/resize-images.sh gallery/in-the-workshop-img
_scripts/resize-images.sh past-events/2014-ACTAA-Scale-Rally/img
_scripts/resize-images.sh past-events/2014-Centenary-of-First-Airmail-Flight/img
_scripts/resize-images.sh past-events/2015-Glider-F5P/img
_scripts/resize-images.sh past-events/2016-Anzac-Day/img
_scripts/resize-images.sh past-events/Aerotow/2017/img
_scripts/resize-images.sh past-events/Aerotow/2018/img
_scripts/resize-images.sh past-events/Air-Race/2016/img
_scripts/resize-images.sh past-events/Air-Race/2017/img
_scripts/resize-images.sh past-events/Air-Race/2018/img
_scripts/resize-images.sh past-events/Mammoth-Fly-In/2015/img
_scripts/resize-images.sh past-events/Mammoth-Fly-In/2016/img
_scripts/resize-images.sh past-events/Mammoth-Fly-In/2017/img
_scripts/resize-images.sh past-events/Mammoth-Fly-In/2018/img
_scripts/resize-images.sh past-events/NEFR/2014/img
_scripts/resize-images.sh past-events/NEFR/2015/img
_scripts/resize-images.sh past-events/NEFR/2016/img
_scripts/resize-images.sh past-events/NEFR/2017/img
_scripts/resize-images.sh past-events/NEFR/2018/img
_scripts/resize-images.sh past-events/NSWSAS-Scale-Comp/2016/img
_scripts/resize-images.sh past-events/NSWSAS-Scale-Comp/2018/img
#
